{% set name = "stakesign" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1161f0c9bed845cc0731603ad3d20d3d76193789057033c75b15de9bf03c8b5d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - stakesign = stakesign:main
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - coreutils  # for sha256sum
    - python
    - importlib_metadata >=1.0.0
    - python-dateutil >=2.0.0
    - web3 >=5.0.0
    - docker-py >=4.0.0
    - pygit2 >=1.0.0

test:
  imports:
    - stakesign
  commands:
    - conda install -y wget  # for this test only
    # Downloading LICENSE here has nothing to do with packaging it -- it's coincidentally a file used for this test case.
    - wget https://github.com/mlin/stakesign/raw/main/LICENSE
    - stakesign verify 0xd071c0e8fbcbcab8b92f9098c5250d7e1c003f222c94fe0729669bae02ae3acf

about:
  home: https://github.com/mlin/stakesign
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sign files via blockchain + put your money where your mouth is
  description: |
    Command-line tool for preparing & verifying "staked" file signatures (signed by cryptocurrency wallet & tied to its unspent balance)

extra:
  recipe-maintainers:
    - mlin
